# This file was generated by GoReleaser. DO NOT EDIT.
cask "addiplay-dev" do
  version "0.0.0"

  on_macos do
    on_intel do
      sha256 "a18578e28c70a28126a06ea1000fe3486447a828e09795df60cb1a2fcdbe14f9"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1fa104a4ce0568f5c42a6d841c4aed78f14259b4dfaede867f7d1db175b767c"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9528d7d6fa03b054285d899db27f2151a4d9f8ae82ad2636390098d44d23ea74"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "74dbdbc7b1e7a47095d00fbd002871a3ae8b141796ad9836a3deaee41fcb804d"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_linux_arm64.tar.gz"
    end
  end

  name "addiplay-dev"
  desc "Terminal player for AudioAddict networks — dev build (rolling)"
  homepage "https://github.com/dimmkirr/addiplay"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "addiplay",
    ]

  depends_on formula: [
      "mpv",
    ]

  binary "addiplay"

  zap trash: [
      "~/Library/Application Support/addiplay",
      "~/.config/addiplay",
    ]

end
