# This file was generated by GoReleaser. DO NOT EDIT.
cask "addiplay-dev@0.0.0" do
  version "0.0.0"

  on_macos do
    on_intel do
      sha256 "334c5a9f3391a91503a784beaed2f15063095f4a2c391b09f199d1a6869d0176"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "319f6fa2d8c15c0c7f0a42036eb2b1e2ef59461a1373d8c64327128316e62d3f"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "139e5740e987c9a4ad5e5d63530094430e079d5aac9e229103423435add71d95"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "769d55685470f48d2f368dcb041bca1bcf08c0c1645a28398649f3302b252ef0"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_linux_arm64.tar.gz"
    end
  end

  name "addiplay-dev@0.0.0"
  desc "Terminal player for AudioAddict networks — pinned dev build 0.0.0"
  homepage "https://github.com/dimmkirr/addiplay"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "addiplay",
    ]

  depends_on formula: [
      "mpv",
    ]

  binary "addiplay"

  # No zap stanza required

end
