# This file was generated by GoReleaser. DO NOT EDIT.
cask "addiplay-dev@0.0.0" do
  version "0.0.0"

  on_macos do
    on_intel do
      sha256 "c21f3d232bae879650903b115f256ab2cc167d57b7c934f9b74dfb57011a26c9"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "02c321c580a1279219238641410754544baf6c7803cbfc723d8d1eda2cf73aa6"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "79fd513694cccfbf575ec2e35f2f070c9934519c14fd6fe739d715ac18f646ad"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6f9f4a54d955273993ba199e424c813b45d36ba7d03503c26c9a92454163708"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_linux_arm64.tar.gz"
    end
  end

  name "addiplay-dev@0.0.0"
  desc "Terminal player for AudioAddict networks — pinned dev build 0.0.0"
  homepage "https://github.com/dimmkirr/addiplay"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "addiplay",
    ]

  depends_on formula: [
      "mpv",
    ]

  binary "addiplay"

  # No zap stanza required

end
