# This file was generated by GoReleaser. DO NOT EDIT.
cask "addiplay-dev" do
  version "0.0.0"

  on_macos do
    on_intel do
      sha256 "4dae426422f68e8afcdc55394319ed8451b480b66dc1c9f7487a75e674545a12"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "941ff8feb094ed1fb1a8e3a5fe1c9a020f8a4f869506d32f1628e796f4cd4e69"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "15faafaf0a7b1ddbd5d1ef40fdf843f8ae3ad3c9f01edafcc24f66ccc2cabe9c"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "61b4c2ae0ac2c203de2e1912c0bbe4c14ae89de04b812a6b6fbf7b95a26fcc47"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_linux_arm64.tar.gz"
    end
  end

  name "addiplay-dev"
  desc "Terminal player for AudioAddict networks — dev build (rolling)"
  homepage "https://github.com/dimmkirr/addiplay"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "addiplay",
    ]

  depends_on formula: [
      "mpv",
    ]

  binary "addiplay"

  zap trash: [
      "~/Library/Application Support/addiplay",
      "~/.config/addiplay",
    ]

end
