# This file was generated by GoReleaser. DO NOT EDIT.
cask "addiplay@0.3.0" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "e03b4c281368dc5dcc75ad0f3950cda8d0b1aa7d41ab3e7646c65cfc97568322"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "117023b85426c15dc91ffe489deb5993962384026d446e1cdd672ff76a390c1c"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "02877fb35b5c49cb0ad6c805cfa112dee46bc5681f77bde634e552452dfeda03"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b1968afb03acef6aeb05d60b794eaa47f77a5829609d34dbef076ea66a1e42e"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}_linux_arm64.tar.gz"
    end
  end

  name "addiplay@0.3.0"
  desc "Terminal player for AudioAddict networks (DI.fm, RockRadio, JazzRadio, …) — pinned to 0.3.0"
  homepage "https://github.com/dimmkirr/addiplay"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "addiplay-dev",
    ]

  depends_on formula: [
      "mpv",
    ]

  binary "addiplay"

  # No zap stanza required

end
