# This file was generated by GoReleaser. DO NOT EDIT.
cask "addiplay" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "801abd4343519626ce6351eae2d1fc7883b12ae68445a687113ebc4b4f8014d2"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c54def8f636c2679866120ef24b01391880a72fb2f751bf9e08c03b357c2131"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "262234cda630391d3b9d771577cda95b9e36463336692970026bbe366e8b3cca"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b8d7000b154335a9a6071a3d0a194dd3a168d69a371f6ad597f96e4a25883da1"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}_linux_arm64.tar.gz"
    end
  end

  name "addiplay"
  desc "Terminal player for AudioAddict networks (DI.fm, RockRadio, JazzRadio, …)"
  homepage "https://github.com/dimmkirr/addiplay"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "addiplay-dev",
    ]

  depends_on formula: [
      "mpv",
    ]

  binary "addiplay"

  zap trash: [
      "~/Library/Application Support/addiplay",
      "~/.config/addiplay",
    ]

end
