# This file was generated by GoReleaser. DO NOT EDIT.
cask "addiplay" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 :no_check # filled in by goreleaser on real release
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 :no_check
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 :no_check
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 :no_check
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}_linux_arm64.tar.gz"
    end
  end

  name "addiplay"
  desc "Terminal player for AudioAddict networks (DI.fm, RockRadio, JazzRadio, …)"
  homepage "https://github.com/dimmkirr/addiplay"

  livecheck do
    skip "Auto-generated on release."
  end

  conflicts_with cask: [
      "addiplay-dev",
    ]

  depends_on formula: "mpv"

  binary "addiplay"

  zap trash: [
    "~/Library/Application Support/addiplay",
    "~/.config/addiplay",
  ]
end
