# This file was generated by GoReleaser. DO NOT EDIT.
cask "addiplay-dev" do
  version "0.0.0"

  on_macos do
    on_intel do
      sha256 "3d1fce31e17945bfd486f2a20f7c8bcccd0e5ef807ae02ea377f62525edf93a3"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2fbc396fe835bd301692b501481f0240360f527f5b270844e3c50a9fb91f0e37"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "266f9a311f67aea895cd0c751abf7c6d0704a570ffe7f50d9dca12910653bc3b"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "44f021d20b639108a4c71a963746684b1fe27b65a303606032e069bab65e0906"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_linux_arm64.tar.gz"
    end
  end

  name "addiplay-dev"
  desc "Terminal player for AudioAddict networks — dev build (rolling)"
  homepage "https://github.com/dimmkirr/addiplay"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "addiplay",
    ]

  depends_on formula: [
      "mpv",
    ]

  binary "addiplay"

  zap trash: [
      "~/Library/Application Support/addiplay",
      "~/.config/addiplay",
    ]

end
