# This file was generated by GoReleaser. DO NOT EDIT.
cask "addiplay-dev@0.0.0" do
  version "0.0.0"

  on_macos do
    on_intel do
      sha256 "844ebadbe9c95996023b22da7f3082a866c20cd59f5d2483ba9f9c7f2531c519"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aeebfe91963d01f21566cb069c5616e8d1e0f658a047493a191c36fdb47c133c"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca84830717a35630ac1b43ff335f1669042cb9d3912e88c9903ef31af8bfd672"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6bc7227b0303e7f9920b7e60c46ae53468c4eb438ae531c921e0c4ccdd8fa1e0"
      url "https://github.com/dimmkirr/addiplay/releases/download/v#{version}/addiplay_#{version}-dev_linux_arm64.tar.gz"
    end
  end

  name "addiplay-dev@0.0.0"
  desc "Terminal player for AudioAddict networks — pinned dev build 0.0.0"
  homepage "https://github.com/dimmkirr/addiplay"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "addiplay",
    ]

  depends_on formula: [
      "mpv",
    ]

  binary "addiplay"

  # No zap stanza required

end
