# This file was generated by GoReleaser. DO NOT EDIT.
cask "cell-dev@0.0.0" do
  name "cell-dev@0.0.0"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "a469c371f5459effb81da63ca675d43d546cf1a75e578a2ab6048b6ea165291f"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "3194c90497acad389691d0afa5cb7ac831ac8086f7a9d848d656c38eb8e30ab7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "b7e0c111f4501b496eaf0e1194365d6538086085ada1e07dfbd7e3a533488bba"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "1adf67194a3ab31d5d788b74f5900e3ee52429b34c7b6b2449625d646dc93316"
    end
  end

  conflicts_with cask: [
      "cell",
    ]

  # No zap stanza required
end
