# This file was generated by GoReleaser. DO NOT EDIT.
cask "cell-dev@0.0.0" do
  name "cell-dev@0.0.0"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "a198b1f7fd929fe767688ab644dcc178d7bb7aa81578c41f97275ca135312bd2"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "f98ce48b99941e6a7811da9b45fd6c35e86f656267edb5cb84eb8b5c444e6ee3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "bdd4812871fc26d2f4efc0cb356742e1d5aeac345c24770c0a7af63e01d8cdf9"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "bd19bcc532980196a1c9788c9d7091e9a33f67980fdab3290c95b3225f5dc23a"
    end
  end

  conflicts_with cask: [
      "cell",
    ]

  # No zap stanza required
end
