# This file was generated by GoReleaser. DO NOT EDIT.
cask "cell-dev@0.0.0" do
  name "cell-dev@0.0.0"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "c0115957fc0e6f21cda63a56b71be41622219a05ad3d75d96177bef9bdae8292"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "b42dea0acc43c4cf83a8405f03b4219f9d496bb1c2b60c38c2a0af02db7f806b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "2fc219660ccc146784b4def178e8fe50d38fd97e06ab426a3ced7e4f2943c6c8"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "d065b1954fc323637c7daffd5d3874253c2427fde92d452577717839eaffb70c"
    end
  end

  conflicts_with cask: [
      "cell",
    ]

  # No zap stanza required
end
