# This file was generated by GoReleaser. DO NOT EDIT.
cask "cell-dev" do
  name "cell-dev"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "f3f976805faa6bea61f9b0edec63dab6ec266ecbe0a6a004d1fa5425d2afcd19"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "4e05d7fc834698f4b10070bb65209555ca93f99b96cebd291841d1f896be93f7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "c6a9540caf73e6be4e12ffb2cdb2fd5a704a27c2423a3e43fb1f9d93f6f0bf5f"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "ae937cfdd1ccbe8a5b7c3e5ca06a4b0c869055c13532c9f6574818afffb7b2ba"
    end
  end

  conflicts_with cask: [
      "cell",
    ]

  # No zap stanza required
end
