# This file was generated by GoReleaser. DO NOT EDIT.
cask "cell-dev" do
  name "cell-dev"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "848e67a6aaf20987c9d9307df7254eaf676b919406b1de36b86802d423168bd1"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "cb8c6e0cd28effa91c27002494efa6db7b56549be5f3e1a656d1842975faed6c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "84e214f4f06897dc5269e1800ae8d535e7df9f56bd9f0e99159127a71ab16c8a"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "5a0c42e765b0bb557d541738f24a6861b079f1b65873b98d213d85e15073cec7"
    end
  end

  conflicts_with cask: [
      "cell",
    ]

  # No zap stanza required
end
