# This file was generated by GoReleaser. DO NOT EDIT.
cask "cell-dev" do
  name "cell-dev"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "455dba146e473b9a945af869ee3a5fca2bba195a8b1a724014b09df76cf8974a"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "8bd7ae40490d12fad3299a9c3c25bbdd72c26e6c0ee7341ffc242bbbacdb6316"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "61405a09158ec524727e2065bac208c4eaa176b114fbfc111921c9721963a63a"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "e6c153008c24a13eac258cc885fea22b79671a3f93891449bb49397624a057c4"
    end
  end

  conflicts_with cask: [
      "cell",
    ]

  # No zap stanza required
end
