# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell-dev" do
  name "devcell-dev"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "ee1453441a25f791eeb0c52d40a67da6f5c6c69acdae723b0a7b701aab240175"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "4ca8584fe561f6b82fabd5831559c295d0404d7b9ee6bad0e56edc2bb9fa6dd1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "ccd43b77c9963ad141cafa76524a4be01b8cafa496121460c7173726ce1f0a75"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "cd4596af4a9c6d2bb9774c7b4d9e6e422b6665f1f43289ac63ae9088d2b13652"
    end
  end

  conflicts_with cask: [
      "devcell",
    ]

  # No zap stanza required
end
