# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell" do
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "ab14c476c504796c2f875e69db8c3c1e11c3ff8498aea5ec04adc265a7632d20"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "be8862d033d83e23b57d12026564d62c0615f2b2584030312148aa6599a27173"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "23b8d0350a71d664815ec17d8fb9a549bb91733d2102e1b520f680d38a85ffc3"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "590aab701e2e43e3b7467bcf97a3cddb9125c30c7cbaae7f111868a821164d41"
    end
  end

  name "devcell"
  desc "Run AI coding agents in a consistent Docker dev environment"
  homepage "https://github.com/DimmKirr/devcell"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "devcell-dev",
    ]

  binary "cell"

  # No zap stanza required

end
