# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell-dev@0.0.0" do
  name "devcell-dev@0.0.0"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "67f6f9dd725ed5ff0254b65c58375b2889b9c9b5c8548da59d7e5d1c8e8ae70d"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "c1440b85b6a281d65b61be94b988e676942f7640557cdf49c367e7e517e08d44"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "5fee7b55dfd4cfd53320c5cf029a31125ccd18c2e6c0df6fa692126493c8254e"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "a43e87ed30e2d223c0af85fdc4d24b4a81619121470fb86a923a6947db45ab66"
    end
  end

  conflicts_with cask: [
      "devcell",
    ]

  # No zap stanza required
end
