# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell-dev" do
  name "devcell-dev"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "f7899bbbaddd2e87e7e3b7e55b8b23e9f33d2626283316a1dabe64fdee0e4bdc"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "43c062c83dcdaf421169461128aadea9f25023118877dd8606462386c562f43f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "965f42e4d8a28a24f09ea19f4783e6d600423b1e0279409941732e4e181a3547"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "03c0b0af65ea416f2cd84c9593a9b7c82a1b972c072a5254bc2c21bd137d9b44"
    end
  end

  conflicts_with cask: [
      "devcell",
    ]

  # No zap stanza required
end
