# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell-dev@0.0.0" do
  version "0.0.0"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "0a2273a34260d89afcb42e4d48685a1aae6413f6d5723029d205c564f750d6ce"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "04aecd0dc760e9f1a0575766e881a19d5895789368a6ec8d97d1b587e497b17f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "73fa2b74cfec3bd98f6bf7d44fa77657d793ecd2fb59048609d98fa95c133f69"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "5ffbca4635905bcd1444f615a9d591952443a047de4e146fc6dd33cb01a3bddd"
    end
  end

  name "devcell-dev@0.0.0"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/DimmKirr/devcell"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "devcell",
    ]

  binary "cell"

  # No zap stanza required

end
