# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell@0.4.2" do
  version "0.4.2"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "c26009f6bf694f53344069736696ebb2cef043e4969749cf723d0ef0388c9c4c"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "2679a86c53147b5ef775d158d3cb76ec6f1e918659044a756ce7d7f2892a102f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "52f6922e918b2855c4a68af3b5d6f05417409be64d172cad30d148a3408e9aec"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "08a0b5e81c8b8c7124b08e8f519ba0a8ff31e0a962d95db742139c8ee940c913"
    end
  end

  name "devcell@0.4.2"
  desc "Run AI coding agents in a consistent Docker dev environment"
  homepage "https://github.com/DimmKirr/devcell"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "devcell-dev",
    ]

  binary "cell"

  # No zap stanza required

end
