# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell@0.1.0" do
  name "devcell@0.1.0"
  desc "Run AI coding agents in a consistent Docker dev environment"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "38ccb5fdc942f7e030adc5d0fc1da67ce24a49db0d61d5076c8518309baf9d54"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "2ca0bfeeeed357762c04a58ae8d08a7134e3a2fbd05c1ec213a0051c8e836311"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "d0cab2e139f312b10adc088d5ea63b6636877385694b410459db77f34e5a10ec"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "a2ebb2e13b3e0458259ca43f2fd19b870997af4cf5430ad793b1b2b288656fa9"
    end
  end

  conflicts_with cask: [
      "devcell-dev",
    ]

  # No zap stanza required
end
