# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell" do
  version "0.5.0"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "973d97e04a002e8c67e7b372d28028abdc3847c4bb0947b0fa70d2510ea0558d"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "f19eb7abeadb89d944d96673b98da240accb5706f89e8b7365d47159a74fa32d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "3153d6b57b22a3fcee658b5e752475269f826c2324f74e065812c76a930fd43f"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "0fdc40ba7d59aade6496cf1932aa82b2149146a56827322d7016de8a4761f399"
    end
  end

  name "devcell"
  desc "Run AI coding agents in a consistent Docker dev environment"
  homepage "https://github.com/DimmKirr/devcell"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "devcell-dev",
    ]

  binary "cell"

  # No zap stanza required

end
