# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell@0.3.0" do
  name "devcell@0.3.0"
  desc "Run AI coding agents in a consistent Docker dev environment"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "d61274099b86f2a49ac46febca21d3d893a4516073ec906e7d00988f969c1bd2"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "ddf137b0f0e4fedc2255bef91fac294b3f44d95b333822af59db5b6da4d02342"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "00d52138766516e7b55f3b340e25a3c0d9e4bc5d76d8f2454cb0a27bbe85c8db"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "72348473144bcdabf4220d9747bf2dd1143facef946f12e3b637783f0c6415a0"
    end
  end

  conflicts_with cask: [
      "devcell-dev",
    ]

  # No zap stanza required
end
