# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell-dev@0.0.0" do
  name "devcell-dev@0.0.0"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "cb95af433a390d4b14a93510184c3b7dd75b473a920e25c3cf1b3356dcac5f88"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "e32cf1ee599c931a6aa5056ac3ca6f67546e68dbba562593c2c7e65fb2912f02"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "583b3fee57ff636b7098a642b11b491bc3cc6f76b5442580b53cefc9c915b235"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "fb55438b311e0abd9d4a6350b2fb908053bfb840a17fbdc72ce83f2840e31a8e"
    end
  end

  conflicts_with cask: [
      "devcell",
    ]

  # No zap stanza required
end
