# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell@0.4.1" do
  version "0.4.1"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "2c567798c6313a7a986cd4191401c4d2e972033940a638e715cd0903dc0bae42"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "5f26feaab81f8969d59536bcb412f3cac946f8038941d80bbeb15e73708ce0f7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "0bd0f1dc173d8e68bf0298d0d60bb39449384c9063fde1dc7514e5a4b245629d"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "d9fc44b13cb275219c53688acd5d9b21def426d3ff399498679f363eb18eb749"
    end
  end

  name "devcell@0.4.1"
  desc "Run AI coding agents in a consistent Docker dev environment"
  homepage "https://github.com/DimmKirr/devcell"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "devcell-dev",
    ]

  binary "cell"

  # No zap stanza required

end
