# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell-dev" do
  name "devcell-dev"
  desc "Run AI coding agents in a consistent Docker dev environment (dev build)"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "608e8382bd035313f002d9232a165456a08f2ef9739b6e3e7118da647ab6483f"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "e2b36e53d7c4c694cd6575a5896abbffd2cdde3fcc90a48edacc7738eb9721f6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "49a015e2eba7497bef3dc30b9d383ca879d47c83db1f6cefe194d5375d20dd75"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "8e1bd81fcfccb66e12f0fce2a065d0a0ea50cd1007bd2b02ee3990c5239d0722"
    end
  end

  conflicts_with cask: [
      "devcell",
    ]

  # No zap stanza required
end
