# This file was generated by GoReleaser. DO NOT EDIT.
cask "devcell@0.2.0" do
  name "devcell@0.2.0"
  desc "Run AI coding agents in a consistent Docker dev environment"
  homepage "https://github.com/DimmKirr/devcell"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cell"

  on_macos do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-amd64.tar.gz"
      sha256 "99303687d00d6687c325f88c0f373379948b520004162a3bf4d0559319e70ad6"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-darwin-arm64.tar.gz"
      sha256 "8610e64080f9219fcd66d467949054fd9d298f67449825918fc1bb705c11eae0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-amd64.tar.gz"
      sha256 "c8e76664f87015f433f9d866d352507b0dfd25515d7dc6a7c25b2cf8acddf0ca"
    end
    on_arm do
      url "https://github.com/DimmKirr/devcell/releases/download/v#{version}/cell-linux-arm64.tar.gz"
      sha256 "82cfa373c09bfbd3b169c525a0159230e6c87df2b656bef6b868616210bf1c8f"
    end
  end

  conflicts_with cask: [
      "devcell-dev",
    ]

  # No zap stanza required
end
