# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtunDevAT000 < Formula
  desc "atun.io is a simple SSM/SSH tunnel manager"
  homepage "https://github.com/DimmKirr/atun"
  version "0.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-darwin-amd64.tar.gz"
      sha256 "0f203e2905cb9556146bbdb6bdd0a00bf8beaa4553341fade5c0182205c9c3a6"

      define_method(:install) do
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-darwin-arm64.tar.gz"
      sha256 "5cf9219eca21462718cef9f320e6df14b9d006adf79bb4a57eed1274ad805ddb"

      define_method(:install) do
        bin.install "atun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-linux-amd64.tar.gz"
      sha256 "ccdfc5bf87c1785d18c9a7b724863110726d9d2ad623e2f33bf63871924f62b5"
      define_method(:install) do
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-linux-arm64.tar.gz"
      sha256 "2daa8d21ba8df1372a956c1aae58804a7493d9bd6d58a4429fbac83d48542e27"
      define_method(:install) do
        bin.install "atun"
      end
    end
  end

  conflicts_with "atun"
  conflicts_with "atun@0.0.0"

  test do
    system "#{bin}/atun version"
  end
end
