# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtunDevAT000 < Formula
  desc "atun.io is a simple SSM/SSH tunnel manager"
  homepage "https://github.com/DimmKirr/atun"
  version "0.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-darwin-amd64.tar.gz"
      sha256 "b9d0285bc498f79d4eb803aa4cf9283bf1497136c29c33f813ffd9144c9c00aa"

      define_method(:install) do
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-darwin-arm64.tar.gz"
      sha256 "e1a45332a79336d827158dd272f557b2b627fd448a2bc70c54a326cd2f5ecb8a"

      define_method(:install) do
        bin.install "atun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-linux-amd64.tar.gz"
      sha256 "7e197dc36e8327182803aaa393740b31d27590612bba72b00158840a9c4aca50"
      define_method(:install) do
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-linux-arm64.tar.gz"
      sha256 "98590841787f7e00fbd985892693199f9c9cc6b00d94d349b3e6940d7319ef79"
      define_method(:install) do
        bin.install "atun"
      end
    end
  end

  conflicts_with "atun"
  conflicts_with "atun@0.0.0"

  test do
    system "#{bin}/atun version"
  end
end
