# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtunDev < Formula
  desc "atun.io is a simple SSM/SSH tunnel manager"
  homepage "https://github.com/DimmKirr/atun"
  version "0.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-darwin-amd64.tar.gz"
      sha256 "079f7d8158a6731fc77d60dc9b5dbd5591112be486e8acebab637437b46e3441"

      define_method(:install) do
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-darwin-arm64.tar.gz"
      sha256 "1e3955b66b70ad9e2c2776b669f46750d7a5f084ea97c8617d058a4ca3fee696"

      define_method(:install) do
        bin.install "atun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-linux-amd64.tar.gz"
      sha256 "50de484cfa3206413d8cce5b23b219d2b449aa250742fd7273d479f04ed37406"
      define_method(:install) do
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-linux-arm64.tar.gz"
      sha256 "a0136a57b3929036e75f86f196b99a8967fbf1d5d8cf57485855ca0c7378eed6"
      define_method(:install) do
        bin.install "atun"
      end
    end
  end

  conflicts_with "atun"
  conflicts_with "atun@0.0.0"

  test do
    system "#{bin}/atun version"
  end
end
