# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtunDevAT000 < Formula
  desc "atun.io is a simple SSM/SSH tunnel manager"
  homepage "https://github.com/DimmKirr/atun"
  version "0.0.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-darwin-amd64.tar.gz"
      sha256 "6b8e572a2083ee8ddb909b084d69fc39a188e2b030b2e2c38ed1d133049a6f98"

      define_method(:install) do
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-darwin-arm64.tar.gz"
      sha256 "82544ea018ba529b1957ebeea7429fd693fe37b98213db6c867eada9f56b0072"

      define_method(:install) do
        bin.install "atun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-linux-amd64.tar.gz"
      sha256 "a7927f33715c7dde7ede2dbded5c4bec3b7da2b2034932e23b0fa732d6ef42a2"
      define_method(:install) do
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DimmKirr/atun/releases/download/v0.0.0/atun-linux-arm64.tar.gz"
      sha256 "3c5957fdec8c2100f2ce275e076bbf4d91cd89da59daded9b0a03e12ad4bc4c3"
      define_method(:install) do
        bin.install "atun"
      end
    end
  end

  conflicts_with "atun"
  conflicts_with "atun@0.0.0"

  test do
    system "#{bin}/atun version"
  end
end
